jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t jeverd/liteboard-express .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin  # (4)
          docker push jeverd/liteboard-express
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          cd docker
          ls
          docker build -t jeverd/liteboard-ngnix .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin  # (4)
          docker push jeverd/liteboard-ngnix 
          
      # - run:
      #     name: 'Deploy to AWS EC2 INSTANACE'
      #     command: |    
      #       echo 'Deploying to EC2'
      #       echo 'ec2-35-183-20-250.ca-central-1.compute.amazonaws.com' >> ~/.ssh/known_hosts
      #       ssh -o StrictHostKeyChecking=no ec2-user@ec2-35-183-20-250.ca-central-1.compute.amazonaws.com "./deploy.sh"
  tests:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: 'Running tests'
          command: |
            echo 'running npm install'
            npm install
            echo 'starting up redis now'
            cd docker
            docker-compose up -d
            echo 'now running tests'
            cd ..
            npm test

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - dev
                - dockerUPdate
      - tests
          
