version: '3.3'
services:
    redis_db:
      image: redis:4.0-alpine
      command: redis-server --requirepass REDIS_PASSWORD_IMPORTANT_KEEP_SAFE
      ports:
        - 6379:6379
      volumes:
        - ./docker-config/redis.conf:/redis.conf
      command: [ "redis-server", "/redis.conf" ]
