version: '3.3'
services:
    redis:
      image: redis:4.0-alpine
      ports:
        - 6379:6379
      volumes:
        - ./docker-config/redis.conf:/redis.conf
      command: [ "redis-server", "/redis.conf" ]
    web-server:
      image: jeverd/liteboard-ngnix:latest
      ports:
        - 80:80
      volumes:
        - ./letsencrypt:/etc/letsencrypt
    app:
      image: jeverd/liteboard-express:latest
      ports:
        - "8080:8080"
      depends_on:
        - redis
        - web-server